In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv("customer_shopping_behavior.csv") # read the csv file
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [7]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [9]:
df.describe().round(2) # to chewk the summary stastices.
# df.describe(include = 'all') for the categoy column also.

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.00,3900.00,3900.00,3863.00,3900.00
mean,1950.50,44.07,59.76,3.75,25.35
std,1125.98,15.21,23.69,0.72,14.45
min,1.00,18.00,20.00,2.50,1.00
25%,975.75,31.00,39.00,3.10,13.00
50%,1950.50,44.00,60.00,3.80,25.00
75%,2925.25,57.00,81.00,4.40,38.00
max,3900.00,70.00,100.00,5.00,50.00

In [10]:
df.isnull().sum() # chewking the null values

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [11]:
# fill the missing value of riview coloum 

df["Review Rating"] = df.groupby("Category")["Review Rating"].transform(lambda x : x.fillna(x.median()))

# under this we can impute the missing value with the category group wise by median . using the transform and the lambda function .

In [13]:
df.isnull().sum() # now the missing value is fill .

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [18]:
df.columns = df.columns.str.lower() # make the all column name into a lower case.
df.columns = df.columns.str.replace(' ','_') # replace (customer id) to (customer_id) all columns.
df = df.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'}) # rename the pruchase amount coloum.

In [21]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [22]:
df["purchase_amount"]

0       53
1       64
2       73
3       90
4       49
        ..
3895    28
3896    49
3897    33
3898    77
3899    81
Name: purchase_amount, Length: 3900, dtype: int64

In [25]:
# create a (age_group) coloum

labels = ['Young Adult', 'Adult' , 'Middle-Age' , 'senoir']
df['age_group'] = pd.qcut(df['age'], q=4 , labels = labels)

# using the pd.qcut  ,  they are split he age into 4 group according the data distrubution , lables
# TO UNDER STAND THE CUSTOMER BEHAVIOUR BY AGE_GROUP

In [28]:
df[['age' , 'age_group']].head(10)

   age    age_group
0   55   Middle-Age
1   19  Young Adult
2   50   Middle-Age
3   21  Young Adult
4   45   Middle-Age
5   46   Middle-Age
6   63       senoir
7   27  Young Adult
8   26  Young Adult
9   57   Middle-Age

In [38]:
# CREATE COLOUMN PURCHASE FREQUENCY DAYS 
frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Quarterly' : 90,
    'Bi-Weekly': 14,
    'Annually' :365,
    'Every 3 Months' :90 
}

df["purchase_frequency_days"] = df["frequency_of_purchases"].map(frequency_mapping)

In [40]:
df[["purchase_frequency_days" , "frequency_of_purchases"]].head(10)
# the bettter under the customer frequency analysis in the formate oof the number and as compare to text , super use for the analysis

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [48]:
# remove the promocode coloum 
(df["discount_applied"]== df["promo_code_used"]).all()

# then drop the promodcodeuser coloum

df = df.drop("promo_code_used", axis=1)

KeyError: 'promo_code_used'

In [49]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [53]:
# to connect the pythone and sql
# instal the pip 

%pip install mysql-connector-python sqlalchemy

Collecting mysql-connector-python
  Downloading mysql_connector_python-26.10.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: sqlalchemy in c:\users\om thawait\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\om thawait\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\om thawait\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading mysql_connector_python-26.10.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/17.7 MB 2.4 MB/s eta 0:00:08
   -- ------------------------------------- 1.0/17.7 MB 2.3 MB/s eta 0:00:08
   -- ------------------------------------- 1.3/17.7 MB 2.2 MB/s eta 0:00:08
   ---- ----------------------------------- 2.1/17.7 MB 2.5 MB/s eta 0:00:07
   ------ --------------------------------- 2.9/17.7 MB 2.7 MB/s eta 0:00:06
   -------- ------------------------------- 3.7/17.7 MB 2.9 MB/s eta 0:00:05
   ---------- ----------------------------- 4.7/17.7 MB 3.2 MB/s eta 0:00:05
   ------------ --------------------------- 5.5/17.7 MB 3.3 MB/s eta 0:00:04
   -------------- ------------------------- 6.6/17.7 MB 3.4 MB/s eta 0:00:04
   ----------------- ---------------------- 7.6/17.7 MB 3.6 MB/s eta 0:00:03
   ------------------- -------------------- 8.7/17.7 MB 3.7 MB/s eta 0:00:03
   ---------------------- ----------------- 10.0/17.7 MB 3.8 MB/s eta 0:00:03
   ------------------------- -------------- 11.3/17.7 MB 4.0 MB/s eta 0:00:02
   ---------------------------- ----------- 12.6/17.7 MB 4.2 MB/s eta 0:00:02
   ------------------------------ --------- 13.6/17.7 MB 4.2 MB/s eta 0:00:01
   --------------------------------- ------ 14.7/17.7 MB 4.3 MB/s eta 0:00:01
   ------------------------------------ --- 16.0/17.7 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------  17.3/17.7 MB 4.5 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 4.4 MB/s  0:00:04
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-26.10.0
Note: you may need to restart the kernel to use updated packages.

In [55]:
from sqlalchemy import create_engine

# step 1:   connect the  workbench sql
username = "root"
password = "Om12345"
host = "localhost"
port = "3306"
database = "project_customer_beh"

# create the engine with sql details

engine = create_engine(f"mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}")

# lode the data set into a sql workbench

table_name = "customer"
df.to_sql(table_name , engine , if_exists = "replace" , index = False)


print(f" data sucessfull lodade into '{table_name}' in the database '{database}'.")

 data sucessfull lodade into 'customer' in the database 'project_customer_beh'.